### ISSUE TITLE
Missing "WCO18_hallwayWalk_004.jpg" file

### ISSUE THREAD

**Issue by pkskelly** [waldekmastykarz/pnp-starterkit-setup#1]
Script stopped at _setup-portal.sh.  The WCO18_hallwayWalk_004.jg file is missing.  

I copied a simple jpg, renamed and added 'WCO18_hallwayWalk_004.jpg' in _setup-portal.sh at line 298.

Restarted script using checkPoint 100 and script continued.

**Comment by waldekmastykarz** [comment]
Added the missing image. I don't have the original and couldn't find it the Starter Kit either so copied one of the existing images instead for now.

**Comment by pkskelly** [comment]
@waldekmastykarz this is still not resolved.  After pulling latest, the file is now there, but the issue also needs the addition of the file name in the files array declaration at line 292 in _setup-portal.sh

**Comment by waldekmastykarz** [comment]
Updated. Sorry for missing it 👍
