### ISSUE TITLE
Provisioning Pages fails in _setup-portal.sh

### ISSUE THREAD

**Issue by pkskelly** [waldekmastykarz/pnp-starterkit-setup#2]
During the Provisioning Pages (starting at line 345), the file provisioning begins but fails at line 381 indicating the `-title` option is invalid.  

![pnp-kit-err2](https://user-images.githubusercontent.com/5527235/50388068-c8ea9f00-06d9-11e9-8e92-84072457da4d.png)

Updating line to `o365 spo page add --webUrl $portalUrl --name $pageName --layoutType $layout $promote --publish` completes the provisioning of all *aspx pages.

**Comment by pkskelly** [comment]
Looks like this may not be an issue.  Update to most recent release seems to have the option.

**Comment by waldekmastykarz** [comment]
This is indeed a recent addition to the CLI. As mentioned in the prerequisites, you need the latest beta, also for the support of adding page content.
