### ISSUE TITLE
Restarting from checkPoint 300 or 400 fails, $hubsiteId undefined. 

### ISSUE THREAD

**Issue by pkskelly** [waldekmastykarz/pnp-starterkit-setup#3]
When restarting the script from --checkPoint 200, the script will complete since $hubsiteId is defined in _setup-portal.sh. 

However when restarting from --checkpoint 300 or 400, the _setup-portal.sh is skipped, and $hubsiteId is undefined. 

To resolve and verify, I added the following in _setup-hr.sh and _setup-marketing.sh:
![checkpoint-changes](https://user-images.githubusercontent.com/5527235/50404348-c8531680-0774-11e9-8600-f30ca42f7d5e.png)

The script proceeds with these changes, but the check should likely be centralized in _functions.sh.

**Comment by pkskelly** [comment]
Just in case you want copy/paste code to start.

```

if [ -z ${hubsiteId+x} ]; then
  sub "Retrieving hubsiteId..."
  result=$(o365 spo hubsite list --output json | jq -r '.[] | select(.SiteUrl == "'"$portalUrl"'") | .ID')
  if [ ! $result ]; then
    error 'ERROR'
    error "Hubsite ID for '$portalUrl' not found"
    exit 1
  fi
  hubsiteId=$result 
  success 'DONE'
fi
```

**Comment by waldekmastykarz** [comment]
Thanks! Let me think what the best way to address this is. Ideally, I'd like all files to be self-contained and don't have dependencies to other files. That will allow us to scale more easily in the future.

**Comment by waldekmastykarz** [comment]
Should be fixed now. The next step will be of course to add more check points along the way, especially with provisioning the portal which is the longest chunk.
