### ISSUE TITLE
Retrieving Site Pages list ID... setup stop execution 

### ISSUE THREAD

**Issue by joaojmendes** [waldekmastykarz/pnp-starterkit-setup#4]
Setup.sh stop execution when trying to get Site Pages list ID.

![screenshot 2018-12-26 at 15 01 19](https://user-images.githubusercontent.com/12551125/50449548-faed4280-091f-11e9-9b7e-f2da2173cd4c.png)

After some tries it stoped in same point with the message:

Provisioning portal site at https://xxxxxxx.sharepoint.com/sites/lcportal...DONE
- Retrieving site ID...DONE
- Retrieving root web ID...DONE
- Retrieving Site Pages list ID...
You can resume the script from the last good state by adding --checkPoint 200

**Comment by joaojmendes** [comment]
I don't know why but the 
sitePagesListId=$(o365 spo list get --webUrl $portalUrl --title 'Site Pages' --output json | jq -r '.Id')

Can't find the list "Site Pages".

I Executed the o365 commands and have the same error.  But the lib exists and have the title "Site Pages".

See print screen

![screenshot 2018-12-26 at 15 23 41](https://user-images.githubusercontent.com/12551125/50450003-ee1e1e00-0922-11e9-8ef2-e15a7f401f3a.png)

**Comment by waldekmastykarz** [comment]
What if you'd execute:

```sh
o365 spo list get --webUrl $portalUrl --title 'Site Pages' --output json | jq -r '.Id'
```

**Comment by joaojmendes** [comment]
Here the result:

![screenshot 2018-12-26 at 22 15 10](https://user-images.githubusercontent.com/12551125/50458555-d616c080-095b-11e9-895c-7167b5a72391.png)

**Comment by waldekmastykarz** [comment]
What if you run only:

```sh
o365 spo list get --webUrl $portalUrl --title 'Site Pages' --output json
```

**Comment by joaojmendes** [comment]
here the result:

![screenshot 2018-12-27 at 10 34 24](https://user-images.githubusercontent.com/12551125/50477213-3c82f980-09c3-11e9-8c3d-96a2df3cdcfe.png)

**Comment by waldekmastykarz** [comment]
What do you get when you execute:

```sh
echo $portalUrl
```

Could it be that somehow the `portalUrl` variable is not set?

**Comment by joaojmendes** [comment]
that's it is blank, the variable is not set

**Comment by waldekmastykarz** [comment]
When you were running the script, did you start from a specific checkpoint or from the beginning? What command did you execute exactly? Did the portal site already exist or was it created by the script?

**Comment by joaojmendes** [comment]
I begin to ran 
 ./setup.sh -t https://xxxx.sharepoint.com -p lc -c lc

The portal site did not exist when a ran the script, it was created by  the script.

After the first stop I ran with checkPoint 

 ./setup.sh -t https://xxxx.sharepoint.com -p lc -c lc --checkPoint 200

**Comment by waldekmastykarz** [comment]
Thanks for the details! Let me see if I can reproduce it.

**Comment by waldekmastykarz** [comment]
I ran the script and it seems to be working just fine for me. If you keep getting the error, could you uncomment in `setup.sh` (line 6):

```sh
set -o xtrace
```

and re-run the script? This should provide you with more details about how commands are run which should help us understand what is wrong.

**Comment by joaojmendes** [comment]
Hi Waldek I  think that I found the problem.

The portal was created in PT Language (2070) , and the title of the List is in Portuguese "Páginas do Site"  not 'Site Pages' , and the command 

o365 spo list get --webUrl $portalUrl --title 'Site Pages' --output json  

returns not found ! :)  it's correct. the script only works on EN Language.

![screenshot 2018-12-27 at 21 29 15](https://user-images.githubusercontent.com/12551125/50495125-21de6e00-0a1f-11e9-962a-87fbe62621e4.png)


![screenshot 2018-12-27 at 21 25 49](https://user-images.githubusercontent.com/12551125/50495179-6cf88100-0a1f-11e9-9a85-4bae6c733236.png)

**Comment by waldekmastykarz** [comment]
Good find! Was the portal created in Portuguese because we don't specify the locale and PT is your default language or did you try to change the script to adapt it to your needs?

**Comment by joaojmendes** [comment]
no I didn't change the script I ran as is . I think that the script must create the site with EN as  default locale.

Thank you very much Waldek, the Provision process is clear and very fast.  it's awesome !

**Comment by waldekmastykarz** [comment]
Thank you for bearing with me and the detailed feedback you've given. I'll check if we could explicitly use en-US locale to avoid similar issues in the future 👏

**Comment by waldekmastykarz** [comment]
@joaojmendes I've extended the `spo site add` command with the ability to specify the language. Would you mind taking a look if it addresses the issue you've experienced if we'd be explicitly setting the language to en-US (1033)? To test the new capability:

- uninstall the previously installed version of the CLI (`npm uninstall -g @pnp/office365-cli`)
- pull my fork @ https://github.com/waldekmastykarz/office365-cli
- switching to the enh-siteadd-lcid branch
- restore dependencies (`npm install`)
- build project (`npm run build`)
- register CLI globally (`npm link`)
- try creating a site using the `spo site add` command with specifying the `lcid` option
- do you still get a site in Portuguese or in English?

After testing, to restore your machine to its original state:
- change working folder to my fork
- run `npm unlink`
- install the regular version of the CLI you've been using previously

Once again, thank you for testing 👏

**Comment by joaojmendes** [comment]
@waldekmastykarz, the site was created in English. very cool. 

Thank you.

**Comment by joaojmendes** [comment]
@waldekmastykarz , I changed the setup script to include the new option lcid on the creation sites and  everything works correct.

**Comment by waldekmastykarz** [comment]
Excellent! Thank you for confirming! The addition to the `site add` command should be available in the next beta. Once it's there, I'll update the setup script. I'll leave this issue open for tracking until then.

**Comment by waldekmastykarz** [comment]
As promised, I've updated the script with the `lcid` option for creating sites. Before you try it out, don't forget to get the latest beta of the Office 365 CLI. Once again, thank you for testing and debugging 👏

**Comment by joaojmendes** [comment]
Thank you ! for me is very good to help and contribute. Thank you @waldekmastykarz  for all support.
