### ISSUE TITLE
Cannot install on Windows machine

### ISSUE THREAD

**Issue by Phentrin** [waldekmastykarz/pnp-starterkit-setup#6]
hello Waldek, 
On my windows Laptop machine, 

 ->I installed Windows Bash
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

 -> I followed the instructions 
On Visual studio code terminal, I connect to O365 & Graph, 
then, I Launch

./setup.sh --tenantUrl https://m365x311235.sharepoint.com --prefix pnp_
A  (linux) bash popup appears then dispappear instantanenously.

I also to launch directly from the linux bash command
./setup.sh --tenantUrl https://m365x311235.sharepoint.com --prefix pnp_

`Output
phentrin@XXXXXXXX:/mnt/c/sources/pnp-starterkit-setup$ ./setup.sh --tenantUrl https://m365x311235.sharepoint.com --prefix pnp_
./setup.sh: line 2: $'\r': command not found
: invalid option nameet: errexit
: invalid option nameet: pipefail
: invalid option nameet: nounset
./setup.sh: line 7: $'\r': command not found
./setup.sh: line 13: $'\r': command not found
: No such file or directoryctions.sh
./setup.sh: line 16: $'\r': command not found
./setup.sh: line 18: msg: command not found
./setup.sh: line 19: $'\r': command not found
: invalid option 20: set: +
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./setup.sh: line 21: $'\r': command not found
./setup.sh: line 29: syntax error near unexpected token `fi'
'/setup.sh: line 29: `fi;`

Am I missing something ?
Thanks.

**Comment by waldekmastykarz** [comment]
I'll need to verify it. I'll get back to you as soon as I know more. Sorry for the trouble

**Comment by waldekmastykarz** [comment]
Sorry, I can't repro it. What I've done:
- installed linux subsystem on Win
- installed the Ubuntu distro
- in Bash, I installed node with npm
- I installed the script prerequisites Office 365 CLI and jq
- I made the setup script executable
- I logged in to my O365 tenant
- I ran the script as described in the readme
- everything seems to be working as expected

**Comment by Phentrin** [comment]
Thanks for the follow up.
I was missing the npm installation ... of course.
Because I was on my Windows 10 machine (with npm already instal) 
I had to install it also on the linux bash as well.

It works perfectly well now !

**Comment by waldekmastykarz** [comment]
Excellent! Thank you for confirming it's working as expected! 👏
