### ISSUE TITLE
HubSites and Team Site not provisioned in setup-hr.sh

### ISSUE THREAD

**Issue by Phentrin** [waldekmastykarz/pnp-starterkit-setup#7]
I launched the script on a Ubuntu machine from Azure
It works well except that the Portal Communication site nor the Teams Sites were created

Also, did not find where the  $alias variable were defined.

for ex: line 43

  groupId=$(o365 graph o365group list --mailNickname **$alias** -o json | jq -r '.[] | select(.mailNickname == "'"$alias"'") | .id')

see output of HR Provisioning

` Configuring navigation...
  - Personal...DONE
  - Organization...DONE
  - Departments...DONE
    - Human Resources...DONE
    - Marketing...DONE
- Configuring extensions...
  - AlertNotification...DONE
  - Redirect...DONE
  - SiteClassification...DONE
  - PortalFooter...DONE
DONE

Provisioning HR site at https://m365x311235.sharepoint.com/sites/pnp_hr...DONE
- Connecting to the hub site...Error: 404 FILE NOT FOUND

You can resume the script from the last good state by adding --checkPoint 310
`

**Comment by waldekmastykarz** [comment]
alias for the HR site is defined here https://github.com/waldekmastykarz/pnp-starterkit-setup/blob/4c647b172578ee1c79c8ef0d5341b24e0e01d337/_setup-hr.sh#L2. Can you repro it every time or was it just a one-off error that could be caused by something like timing or temporary glitch in O365?

**Comment by waldekmastykarz** [comment]
FWIW, I've just ran the provisioning script twice on my tenant and I can't repro your issue, which makes me suspect either a temporary glitch or something specific to your tenant.

**Comment by Phentrin** [comment]
ok, maybe something specific on my  Tenant.
So I will use another tenant to be sure.

Thanks.

**Comment by waldekmastykarz** [comment]
Let's reopen the issue if you still experience problems, ok?
